// This file was generated by github.com/nelsam/hel.  Do not
// edit this code by hand unless you *really* know what you're
// doing.  Expect any changes made manually to be overwritten
// the next time hel regenerates this file.

package v1_test

import (
	"sync"

	"github.com/cloudfoundry/sonde-go/events"
)

type mockConn struct {
	WriteCalled chan bool
	WriteInput  struct {
		Data chan []byte
	}
	WriteOutput struct {
		Ret0 chan error
	}
}

func newMockConn() *mockConn {
	m := &mockConn{}
	m.WriteCalled = make(chan bool, 100)
	m.WriteInput.Data = make(chan []byte, 100)
	m.WriteOutput.Ret0 = make(chan error, 100)
	return m
}
func (m *mockConn) Write(data []byte) error {
	m.WriteCalled <- true
	m.WriteInput.Data <- data
	return <-m.WriteOutput.Ret0
}

type MockByteArrayWriter struct {
	data [][]byte
	lock sync.RWMutex
}

func (m *MockByteArrayWriter) Write(p []byte) {
	m.lock.Lock()
	defer m.lock.Unlock()
	m.data = append(m.data, p)
}

func (m *MockByteArrayWriter) Data() [][]byte {
	m.lock.RLock()
	defer m.lock.RUnlock()
	return m.data
}

func (m *MockByteArrayWriter) Weight() int {
	return 0
}

type mockBatchChainByteWriter struct {
	WriteCalled chan bool
	WriteInput  struct {
		Message chan []byte
	}
	WriteOutput struct {
		Err chan error
	}
}

func newMockBatchChainByteWriter() *mockBatchChainByteWriter {
	m := &mockBatchChainByteWriter{}
	m.WriteCalled = make(chan bool, 100)
	m.WriteInput.Message = make(chan []byte, 100)
	m.WriteOutput.Err = make(chan error, 100)
	return m
}
func (m *mockBatchChainByteWriter) Write(message []byte) (err error) {
	m.WriteCalled <- true
	m.WriteInput.Message <- message
	return <-m.WriteOutput.Err
}

type mockDroppedMessageCounter struct {
	DropCalled chan bool
	DropInput  struct {
		Count chan uint32
	}
}

func newMockDroppedMessageCounter() *mockDroppedMessageCounter {
	m := &mockDroppedMessageCounter{}
	m.DropCalled = make(chan bool, 100)
	m.DropInput.Count = make(chan uint32, 100)
	return m
}
func (m *mockDroppedMessageCounter) Drop(count uint32) {
	m.DropCalled <- true
	m.DropInput.Count <- count
}

type MockEnvelopeWriter struct {
	Events     []*events.Envelope
	eventsLock sync.Mutex
}

func (m *MockEnvelopeWriter) Write(event *events.Envelope) {
	m.eventsLock.Lock()
	defer m.eventsLock.Unlock()
	m.Events = append(m.Events, event)
}
